apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: go-web-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/bryan-obabori/eks-gitops-terraform.git
    targetRevision: main
    path: gitops/go-web-app-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
